In [1]:
import pandas as pd
import re

In [2]:
# Load IPEDS Cost data
# costs_2011 = pd.read_csv(r"C:\capstone_data\raw\ic2011_ay.csv")
costs_2011 = pd.read_csv(r"..\data\raw\ic2011_ay.csv")
# Load College Scorecard Institution Level data
# costs_2021 = pd.read_csv(r"C:\capstone_data\raw\ic2021_ay.csv")
costs_2024 = pd.read_csv(r"..\data\raw\c2024_a.csv")

In [3]:
costs_2011.columns.tolist()

['UNITID',
 'XTUIT1',
 'TUITION1',
 'XFEE1',
 'FEE1',
 'XHRCHG1',
 'HRCHG1',
 'XCMPFEE1',
 'CMPFEE1',
 'XTUIT2',
 'TUITION2',
 'XFEE2',
 'FEE2',
 'XHRCHG2',
 'HRCHG2',
 'XCMPFEE2',
 'CMPFEE2',
 'XTUIT3',
 'TUITION3',
 'XFEE3',
 'FEE3',
 'XHRCHG3',
 'HRCHG3',
 'XCMPFEE3',
 'CMPFEE3',
 'XTUIT5',
 'TUITION5',
 'XFEE5',
 'FEE5',
 'XHRCHG5',
 'HRCHG5',
 'XTUIT6',
 'TUITION6',
 'XFEE6',
 'FEE6',
 'XHRCHG6',
 'HRCHG6',
 'XTUIT7',
 'TUITION7',
 'XFEE7',
 'FEE7',
 'XHRCHG7',
 'HRCHG7',
 'XISPRO1',
 'ISPROF1',
 'XISPFE1',
 'ISPFEE1',
 'XOSPRO1',
 'OSPROF1',
 'XOSPFE1',
 'OSPFEE1',
 'XISPRO2',
 'ISPROF2',
 'XISPFE2',
 'ISPFEE2',
 'XOSPRO2',
 'OSPROF2',
 'XOSPFE2',
 'OSPFEE2',
 'XISPRO3',
 'ISPROF3',
 'XISPFE3',
 'ISPFEE3',
 'XOSPRO3',
 'OSPROF3',
 'XOSPFE3',
 'OSPFEE3',
 'XISPRO4',
 'ISPROF4',
 'XISPFE4',
 'ISPFEE4',
 'XOSPRO4',
 'OSPROF4',
 'XOSPFE4',
 'OSPFEE4',
 'XISPRO5',
 'ISPROF5',
 'XISPFE5',
 'ISPFEE5',
 'XOSPRO5',
 'OSPROF5',
 'XOSPFE5',
 'OSPFEE5',
 'XISPRO6',
 'ISPROF6',
 'XISPFE6',
 'ISPFEE6',
 'XOSPRO6',
 'OSPROF6',
 'XOSPFE6',
 'OSPFEE6',
 'XISPRO7',
 'ISPROF7',
 'XISPFE7',
 'ISPFEE7',
 'XOSPRO7',
 'OSPROF7',
 'XOSPFE7',
 'OSPFEE7',
 'XISPRO8',
 'ISPROF8',
 'XISPFE8',
 'ISPFEE8',
 'XOSPRO8',
 'OSPROF8',
 'XOSPFE8',
 'OSPFEE8',
 'XISPRO9',
 'ISPROF9',
 'XISPFE9',
 'ISPFEE9',
 'XOSPRO9',
 'OSPROF9',
 'XOSPFE9',
 'OSPFEE9',
 'XCHG1AT0',
 'CHG1AT0',
 'XCHG1AF0',
 'CHG1AF0',
 'XCHG1AY0',
 'CHG1AY0',
 'XCHG1AT1',
 'CHG1AT1',
 'XCHG1AF1',
 'CHG1AF1',
 'XCHG1AY1',
 'CHG1AY1',
 'XCHG1AT2',
 'CHG1AT2',
 'XCHG1AF2',
 'CHG1AF2',
 'XCHG1AY2',
 'CHG1AY2',
 'XCHG1AT3',
 'CHG1AT3',
 'XCHG1AF3',
 'CHG1AF3',
 'XCHG1AY3',
 'CHG1AY3',
 'CHG1TGTD',
 'CHG1FGTD',
 'XCHG2AT0',
 'CHG2AT0',
 'XCHG2AF0',
 'CHG2AF0',
 'XCHG2AY0',
 'CHG2AY0',
 'XCHG2AT1',
 'CHG2AT1',
 'XCHG2AF1',
 'CHG2AF1',
 'XCHG2AY1',
 'CHG2AY1',
 'XCHG2AT2',
 'CHG2AT2',
 'XCHG2AF2',
 'CHG2AF2',
 'XCHG2AY2',
 'CHG2AY2',
 'XCHG2AT3',
 'CHG2AT3',
 'XCHG2AF3',
 'CHG2AF3',
 'XCHG2AY3',
 'CHG2AY3',
 'CHG2TGTD',
 'CHG2FGTD',
 'XCHG3AT0',
 'CHG3AT0',
 'XCHG3AF0',
 'CHG3AF0',
 'XCHG3AY0',
 'CHG3AY0',
 'XCHG3AT1',
 'CHG3AT1',
 'XCHG3AF1',
 'CHG3AF1',
 'XCHG3AY1',
 'CHG3AY1',
 'XCHG3AT2',
 'CHG3AT2',
 'XCHG3AF2',
 'CHG3AF2',
 'XCHG3AY2',
 'CHG3AY2',
 'XCHG3AT3',
 'CHG3AT3',
 'XCHG3AF3',
 'CHG3AF3',
 'XCHG3AY3',
 'CHG3AY3',
 'CHG3TGTD',
 'CHG3FGTD',
 'XCHG4AY0',
 'CHG4AY0',
 'XCHG4AY1',
 'CHG4AY1',
 'XCHG4AY2',
 'CHG4AY2',
 'XCHG4AY3',
 'CHG4AY3',
 'XCHG5AY0',
 'CHG5AY0',
 'XCHG5AY1',
 'CHG5AY1',
 'XCHG5AY2',
 'CHG5AY2',
 'XCHG5AY3',
 'CHG5AY3',
 'XCHG6AY0',
 'CHG6AY0',
 'XCHG6AY1',
 'CHG6AY1',
 'XCHG6AY2',
 'CHG6AY2',
 'XCHG6AY3',
 'CHG6AY3',
 'XCHG7AY0',
 'CHG7AY0',
 'XCHG7AY1',
 'CHG7AY1',
 'XCHG7AY2',
 'CHG7AY2',
 'XCHG7AY3',
 'CHG7AY3',
 'XCHG8AY0',
 'CHG8AY0',
 'XCHG8AY1',
 'CHG8AY1',
 'XCHG8AY2',
 'CHG8AY2',
 'XCHG8AY3',
 'CHG8AY3',
 'XCHG9AY0',
 'CHG9AY0',
 'XCHG9AY1',
 'CHG9AY1',
 'XCHG9AY2',
 'CHG9AY2',
 'XCHG9AY3',
 'CHG9AY3',
 'XCMP1AY0',
 'CMP1AY0',
 'XCMP1AY1',
 'CMP1AY1',
 'XCMP1AY2',
 'CMP1AY2',
 'XCMP1AY3',
 'CMP1AY3',
 'CMP1GTD',
 'XCMP2AY0',
 'CMP2AY0',
 'XCMP2AY1',
 'CMP2AY1',
 'XCMP2AY2',
 'CMP2AY2',
 'XCMP2AY3',
 'CMP2AY3',
 'CMP2GTD',
 'XCMP3AY0',
 'CMP3AY0',
 'XCMP3AY1',
 'CMP3AY1',
 'XCMP3AY2',
 'CMP3AY2',
 'XCMP3AY3',
 'CMP3AY3',
 'CMP3GTD ']

In [4]:
# Select columns to keep.
costs_2011_clean = costs_2011[[
    "UNITID"
    ,"TUITION2"
    ,"FEE2"
    ,"TUITION3"
    ,"FEE3"
    ,"CHG10"
    ,"CHG1AY1"
    ,"CHG1AY2"
    ,"CHG1AY3"
    ,"CHG2AY0"
    ,"
]].copy()

In [5]:
costs_2011_clean["instate_cost"] = (
    costs_2011_clean["TUITION2"] + costs_2011_clean["FEE2"]
)
costs_2011_clean["outstate_cost"] = (
    costs_2011_clean["TUITION3"] + costs_2011_clean["FEE2"]
)

In [6]:
costs_2011_clean.head(2)

       UNITID TUITION2 FEE2 TUITION3 FEE3 instate_cost outstate_cost
100636      R        Z    R        Z    R           ZR            ZR
100654      R        R    R        R    R           RR            RR

In [7]:
costs_2011_clean.dtypes

UNITID           object
TUITION2         object
FEE2             object
TUITION3         object
FEE3             object
instate_cost     object
outstate_cost    object
dtype: object

In [10]:
costs_2011_clean.columns = costs_2011_clean.columns.str.lower()

for col in ["tuition2", "fee2", "tuition3", "fee3", "instate_cost", "outstate_cost"]:
    costs_2011_clean[col] = pd.to_numeric(
        costs_2011_clean[col],
        errors="coerce"
    )

In [11]:
costs_2011_clean.head(2)

       unitid  tuition2  fee2  tuition3  fee3  instate_cost  outstate_cost
100636      R       NaN   NaN       NaN   NaN           NaN            NaN
100654      R       NaN   NaN       NaN   NaN           NaN            NaN